const alacarteData = [
    {
      id:1,
      img: require('./images/AlaCarte/Agedashidōfu $5.JPG'),
      title: 'Agedashidōfu',
      price:'$5',
      des: '(50% redeemable with points)',
    },
    {
      id:2,
      img: require('./images/AlaCarte/Avocado Hand Roll  $8.JPG'),
      title: 'Avocado Hand Roll',
      price:'$8',
      des: '(50% redeemable with points)',
    },
    {
      id:3,
      img: require('./images/AlaCarte/Avocado with Salmon $14.JPG'),
      title: 'Avocado with Salmon',
      price:'$14',
      des: '(50% redeemable with points)',
    },
    {
      id:4,
      img: require('./images/AlaCarte/Beef Udon $16.JPG'),
      title: 'Beef Udon',
      price:'$16',
      des: '(50% redeemable with points)',
    },
    {
      id:5,
      img: require('./images/AlaCarte/California Roll $12.JPG'),
      title: 'California Roll',
      price:'$12',
      des: '(50% redeemable with points)',
    },
    {
      id:6,
      img: require('./images/AlaCarte/Chawanmushi $5.JPG'),
      title: 'Chawanmushi',
      price:'$5',
      des: '(50% redeemable with points)',
    },
    {
      id:7,
      img: require('./images/AlaCarte/Chirashi Don $22.JPG'),
      title: 'Chirashi Don',
      price:'$22',
      des: '(50% redeemable with points)',
    },
    {
      id:8,
      img: require('./images/AlaCarte/Cold Noodle $12.JPG'),
      title: 'Cold Noodle',
      price:'$12',
      des: '(50% redeemable with points)',
    },
    {
      id:9,
      img: require('./images/AlaCarte/Ebi Fura $12.JPG'),
      title: 'Ebi Fura',
      price:'$12',
      des: '(50% redeemable with points)',
    },
    {
      id:10,
      img: require('./images/AlaCarte/Ebi Mayunezu Yaki $22.JPG'),
      title: 'Ebi Mayunezu Yaki',
      price:'$22',
      des: '(50% redeemable with points)',
    },
    {
      id:11,
      img: require('./images/AlaCarte/Ebi Nigiri Sushi $6.JPG'),
      title: 'Ebi Nigiri Sushi',
      price:'$6',
      des: '(50% redeemable with points)',
    },
    {
      id:12,
      img: require('./images/AlaCarte/Ebi Tempura $18.JPG'),
      title: 'Ebi Tempura',
      price:'$18',
      des: '(50% redeemable with points)',
    },
    {
      id:13,
      img: require('./images/AlaCarte/Edamame $5.JPG'),
      title: 'Edamame',
      price:'$5',
      des: '(50% redeemable with points)',
    },
    {
      id:14,
      img: require('./images/AlaCarte/Fried Fish Ball  $12.JPG'),
      title: 'Fried Fish Ball',
      price:'$12',
      des: '(50% redeemable with points)',
    },
    {
      id:15,
      img: require('./images/AlaCarte/Futoimaki $12.JPG'),
      title: 'Futoimaki',
      price:'$12',
      des: '(50% redeemable with points)',
    },
    {
      id:16,
      img: require('./images/AlaCarte/Gintara Shioyaki $22.JPG'),
      title: 'Gintara Shioyaki',
      price:'$22',
      des: '(50% redeemable with points)',
    },
    {
      id:17,
      img: require('./images/AlaCarte/Grilled Chicken Sushi $8.JPG'),
      title: 'Grilled Chicken Sushi',
      price:'$8',
      des: '(50% redeemable with points)',
    },
    {
      id:18,
      img: require('./images/AlaCarte/Grilled Fish Ball  $8.JPG'),
      title: 'Grilled Fish Ball',
      price:'$8',
      des: '(50% redeemable with points)',
    },
    {
      id:19,
      img: require('./images/AlaCarte/Inarizushi $12.JPG'),
      title: 'Inarizushi',
      price:'$12',
      des: '(50% redeemable with points)',
    },
    {
      id:20,
      img: require('./images/AlaCarte/Japanese Curry Beef Rice $18.JPG'),
      title: 'Japanese Curry Beef Rice',
      price:'$18',
      des: '(50% redeemable with points)',
    },
    {
      id:21,
      img: require('./images/AlaCarte/Japanese Curry Chicken Rice $12.JPG'),
      title: 'Japanese Curry Chicken Rice',
      price:'$12',
      des: '(50% redeemable with points)',
    },
    {
      id:22,
      img: require('./images/AlaCarte/Japanese Curry Ebi Fry RIce $18.JPG'),
      title: 'Japanese Curry Ebi Fry RIce',
      price:'$18',
      des: '(50% redeemable with points)',
    },
    {
      id:23,
      img: require('./images/AlaCarte/Japanese Curry ToriKatsu Rice $12.JPG'),
      title: 'Japanese Curry ToriKatsu Rice',
      price:'$12',
      des: '(50% redeemable with points)',
    },
    {
      id:24,
      img: require('./images/AlaCarte/Japanese Curry Vegetable Rice $12.JPG'),
      title: 'Japanese Curry Vegetable Rice',
      price:'$12',
      des: '(50% redeemable with points)',
    },
    {
      id:25,
      img: require('./images/AlaCarte/Japanese Rice $3.JPG'),
      title: 'Japanese Rice',
      price:'$3',
      des: '(50% redeemable with points)',
    },
    {
      id:26,
      img: require('./images/AlaCarte/Kaki Furai $12.JPG'),
      title: 'Kaki Furai',
      price:'$12',
      des: '(50% redeemable with points)',
    },
    {
      id:27,
      img: require('./images/AlaCarte/Kitsune Udon $12.JPG'),
      title: 'AlKitsune Udon',
      price:'$12',
      des: '(50% redeemable with points)',
    },
    {
      id:28,
      img: require('./images/AlaCarte/Maguro Nigiri Sushi $6.8.JPG'),
      title: 'Maguro Nigiri Sushi',
      price:'$6.8',
      des: '(50% redeemable with points)',
    },
    {
      id:29,
      img: require('./images/AlaCarte/Red and Green Chilli Sushi  $12.JPG'),
      title: 'Red and Green Chilli Sushi',
      price:'$12',
      des: '(50% redeemable with points)',
    },
    {
      id:30,
      img: require('./images/AlaCarte/Saba Shioyaki $12.JPG'),
      title: 'Saba Shioyaki',
      price:'$12',
      des: '(50% redeemable with points)',
    },
    {
      id:31,
      img: require('./images/AlaCarte/Salmon Don $16.JPG'),
      title: 'Salmon Don',
      price:'$16',
      des: '(50% redeemable with points)',
    },
    {
      id:32,
      img: require('./images/AlaCarte/Salmon Nigiri Sushi $6.8.JPG'),
      title: 'Salmon Nigiri Sushi',
      price:'$6.8',
      des: '(50% redeemable with points)',
    },
    {
      id:33,
      img: require('./images/AlaCarte/Salmon Teppanyaki $22.JPG'),
      title: 'Salmon Teppanyaki',
      price:'$22',
      des: '(50% redeemable with points)',
    },
    {
      id:34,
      img: require('./images/AlaCarte/Shiromiso $3.JPG'),
      title: 'Shiromiso',
      price:'$3',
      des: '(50% redeemable with points)',
    },
    {
      id:35,
      img: require('./images/AlaCarte/Spicy Assorted Tempura  $18.JPG'),
      title: 'Spicy Assorted Tempura',
      price:'$18',
      des: '(50% redeemable with points)',
    },
    {
      id:36,
      img: require('./images/AlaCarte/Spicy Assoted Sashimi Sushi Roll $18.JPG'),
      title: 'Spicy Assoted Sashimi Sushi Roll',
      price:'$18',
      des: '(50% redeemable with points)',
    },
    {
      id:37,
      img: require('./images/AlaCarte/Spicy Avocado Sushi $6.JPG'),
      title: 'Spicy Avocado Sushi',
      price:'$6',
      des: '(50% redeemable with points)',
    },
    {
      id:38,
      img: require('./images/AlaCarte/Spicy Banana Roll  $12.JPG'),
      title: 'Spicy Banana Roll',
      price:'$12',
      des: '(50% redeemable with points)',
    },
    {
      id:39,
      img: require('./images/AlaCarte/Spicy California Roll $12.JPG'),
      title: 'Spicy California Roll',
      price:'$12',
      des: '(50% redeemable with points)',
    },
    {
      id:40,
      img: require('./images/AlaCarte/Spicy Cheese Roll   $16.JPG'),
      title: 'Spicy Cheese Roll',
      price:'$16',
      des: '(50% redeemable with points)',
    },
    {
      id:41,
      img: require('./images/AlaCarte/Spicy Chicken Sushi Roll $12.JPG'),
      title: 'Spicy Chicken Sushi Roll',
      price:'$12',
      des: '(50% redeemable with points)',
    },
    {
      id:42,
      img: require('./images/AlaCarte/Spicy Crab Stick Sushi  $5.JPG'),
      title: 'Spicy Crab Stick Sushi',
      price:'$5',
      des: '(50% redeemable with points)',
    },
    {
      id:43,
      img: require('./images/AlaCarte/Spicy Futoimaki  $12.JPG'),
      title: 'Spicy Futoimaki',
      price:'$12',
      des: '(50% redeemable with points)',
    },
    {
      id:44,
      img: require('./images/AlaCarte/Spicy Japanese Pickle Sushi $12.JPG'),
      title: 'Spicy Japanese Pickle Sushi',
      price:'$12',
      des: '(50% redeemable with points)',
    },
    {
      id:45,
      img: require('./images/AlaCarte/Spicy Prawn Sushi  $14.JPG'),
      title: 'Spicy Prawn Sushi',
      price:'$14',
      des: '(50% redeemable with points)',
    },
    {
      id:46,
      img: require('./images/AlaCarte/Spicy Salmon and Avocado Roll  $14.JPG'),
      title: 'Spicy Salmon and Avocado Roll',
      price:'$14',
      des: '(50% redeemable with points)',
    },
    {
      id:47,
      img: require('./images/AlaCarte/Spicy Salmon Roll $14.JPG'),
      title: 'Spicy Salmon Roll',
      price:'$14',
      des: '(50% redeemable with points)',
    },
    {
      id:48,
      img: require('./images/AlaCarte/Spicy Salmon with Crab Stick Roll $14.JPG'),
      title: 'Spicy Salmon with Crab Stick Roll',
      price:'$14',
      des: '(50% redeemable with points)',
    },
    {
      id:49,
      img: require('./images/AlaCarte/Spicy Sauce Sushi  $8.JPG'),
      title: 'Spicy Sauce Sushi',
      price:'$8',
      des: '(50% redeemable with points)',
    },
    {
      id:50,
      img: require('./images/AlaCarte/Spicy Sweet Potato Roll $13.JPG'),
      title: 'Spicy Sweet Potato Roll',
      price:'$13',
      des: '(50% redeemable with points)',
    },
    {
      id:51,
      img: require('./images/AlaCarte/Spicy Tempura Sushi  $16.JPG'),
      title: 'Spicy Tempura Sushi',
      price:'$16',
      des: '(50% redeemable with points)',
    },
    {
      id:52,
      img: require('./images/AlaCarte/Spicy Torikaraage $6.JPG'),
      title: 'Spicy Torikaraage',
      price:'$6',
      des: '(50% redeemable with points)',
    },
    {
      id:53,
      img: require('./images/AlaCarte/Spicy Tuna Roll $14.JPG'),
      title: 'Spicy Tuna Roll',
      price:'$14',
      des: '(50% redeemable with points)',
    },
    {
      id:54,
      img: require('./images/AlaCarte/Spicy Tuna with Avocado   $8.JPG'),
      title: 'Spicy Tuna with Avocado',
      price:'$8',
      des: '(50% redeemable with points)',
    },
    {
      id:55,
      img: require('./images/AlaCarte/Sushi Roll Platter $8.JPG'),
      title: 'Sushi Roll Platter',
      price:'$8',
      des: '(50% redeemable with points)',
    },
    {
      id:56,
      img: require('./images/AlaCarte/Tako Nigiri Sushi $6.JPG'),
      title: 'Tako Nigiri Sushi',
      price:'$6',
      des: '(50% redeemable with points)',
    },
    {
      id:57,
      img: require('./images/AlaCarte/Tamago $8.JPG'),
      title: 'Tamago',
      price:'$8',
      des: '(50% redeemable with points)',
    },
    {
      id:58,
      img: require('./images/AlaCarte/Tamago Nigiri Sushi $5.JPG'),
      title: 'Tamago Nigiri Sushi',
      price:'$5',
      des: '(50% redeemable with points)',
    },
    {
      id:59,
      img: require('./images/AlaCarte/Tekka Don $18.JPG'),
      title: 'Tekka Don',
      price:'$18',
      des: '(50% redeemable with points)',
    },
    {
      id:60,
      img: require('./images/AlaCarte/Tempura Sush $15.JPG'),
      title: 'Tempura Sush',
      price:'$15',
      des: '(50% redeemable with points)',
    },
    {
      id:61,
      img: require('./images/AlaCarte/Tempure Don $12.JPG'),
      title: 'Tempure Don',
      price:'$12',
      des: '(50% redeemable with points)',
    },
    {
      id:62,
      img: require('./images/AlaCarte/Unagi Don $22.JPG'),
      title: 'Unagi Don',
      price:'$22',
      des: '(50% redeemable with points)',
    },
    {
      id:63,
      img: require('./images/AlaCarte/Unagikabayaki $22.JPG'),
      title: 'Unagikabayaki',
      price:'$22',
      des: '(50% redeemable with points)',
    },
    {
      id:64,
      img: require('./images/AlaCarte/Wakame Udon $12.JPG'),
      title: 'Wakame Udon',
      price:'$12',
      des: '(50% redeemable with points)',
    },
    {
      id:65,
      img: require('./images/AlaCarte/Wasabi Chicken Sushi $12.JPG'),
      title: 'Wasabi Chicken Sushi',
      price:'$12',
      des: '(50% redeemable with points)',
    },
    {
      id:66,
      img: require('./images/AlaCarte/Yakiniku Don $22.JPG'),
      title: 'Yakiniku Don',
      price:'$22',
      des: '(50% redeemable with points)',
    },
    {
      id:67,
      img: require('./images/AlaCarte/Yakitori Don $12.JPG'),
      title: 'Yakitori Don',
      price:'$12',
      des: '(50% redeemable with points)',
    }

  ];

  const setData = [
    {
      id:1,
      img: require('./images/Sets/1-FOR-1 Beef Set $48.jpg'),
      title: '1-FOR-1 Beef Set',
      price:'$48',
      des: '(20% redeemable with points)',
    },
    {
      id:2,
      img: require('./images/Sets/1-FOR-1 Unagi Set $48.jpg'),
      title: '1-FOR-1 Unagi Set',
      price: '$48',
      des: '(20% redeemable with points)',
    },
    {
      id:3,
      img: require('./images/Sets/Ala Carte Buffet $56-98.jpg'),
      title: 'Ala Carte Buffet',
      price:'$56-$98',
      des: '(40% redeemable with points)',
    },
    {
      id:4,
      img: require('./images/Sets/Beef Dinner Set $45.jpg'),
      title: 'Beef Dinner Set',
      price: '$45',
      des: '(20% redeemable with points)',
    },
    {
      id:5,
      img: require('./images/Sets/Cod Fish Set $38.jpg'),
      title: 'Cod Fish Set',
      price: '$38',
      des: '(20% redeemable with points)',
    },
    {
      id:6,
      img: require('./images/Sets/Lobster Set $78.jpg'),
      title: 'Lobster Set',
      price: '$78',
      des: '(20% redeemable with points)',
    },
    {
      id:7,
      img: require('./images/Sets/Lunch Saba Set $12.jpg'),
      title: 'Lunch Saba Set',
      price: '$12',
      des: '(20% redeemable with points)',
    },
    {
      id:8,
      img: require('./images/Sets/Premium Set $45.jpg'),
      title: 'Premium Set',
      price: '$45',
      des: '(20% redeemable with points)',
    },
    {
      id:9,
      img: require('./images/Sets/Sashimi Saba TorikKatsu Dinner Set $26.jpg'),
      title: 'Sashimi Saba TorikKatsu Dinner Set',
      price: '$26',
      des: '(20% redeemable with points)',
    },
    {
      id:10,
      img: require('./images/Sets/Sushi Set $22.jpg'),
      title: 'Sushi Set',
      price: '$22',
      des: '(20% redeemable with points)',
    },
    {
      id:11,
      img: require('./images/Sets/Tempura Udon Set $18.jpg'),
      title: 'Tempura Udon Set',
      price: '$18',
      des: '(20% redeemable with points)',
    },
    {
      id:12,
      img: require('./images/Sets/Unagi Dinner Set $38.jpg'),
      title: 'Unagi Dinner Set',
      price: '$38',
      des: '(20% redeemable with points)',
    }
  ]; 

  export default {
    getAlaCarteMenu() {
      return alacarteData;
    },
    getSetMenu() {
      return setData;
    }
  };